name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install http-server --save-dev
      
      # Start the HTTP server
      - name: Start HTTP Server
        run: |
          npx http-server ./src -p 8080 &
        shell: bash

      # Run tests
      - name: Run Tests
        run: npm test
      
      # Stop the HTTP server (This will run even if the previous steps fail)
      - name: Stop HTTP Server
        if: always()
        run: |
          kill $(lsof -t -i:8080)
        shell: bash
